const dataList = [
    {
        id: "13031_2092179265",
        name: "Duo Aeropuerto",
        description:
            "1 Aeropuerto cecina, 1 aeropuerto lomo saltado, 2 gaseosas 500ml a elección. promoción válida del 19/09/2023 hasta 31/10/2023. stock mínimo de 100 unidades. razon social: alert del peru s.a. y ruc: 20101869947.",
        image: "tmp223470339775700406804243205.png",
        index: 1,
        tablecloth: "tablecloth.png",
        need_image: true,
        need_topping: true,
        has_toppings: true,
        has_recommendations: false,
        is_available: false,
        corridor_id: 172939,
        corridor_name: "Promociones ",
        corridor_index: 1,
        real_price: 65.6,
        price: 65.6,
        schedules: [
            {
                open_time: "10:30:00",
                close_time: "22:00:00",
            },
        ],
        discount_from_go: false,
        store_id: 13031,
        product_id: 2092179265,
        store_name: "",
        quantity: 1,
        is_open_forever: false,
        has_up_sellings: false,
        is_liked: false,
        topping_list: [],
        comment: "",
        have_discount: false,
        second_layer: "",
        quantity_bought: 0,
        is_popular: false,
        super_store_id: 12136,
        brand_name: "",
        in_schedule: true,
        elastic_version: 0,
        last_updated: 1696532677668,
        show_discount_tag: true,
        dietary_restrictions: null,
        discount_percentage: 0,
        minimum_price: -1,
        minimum_price_text: null,
        discounts: [
            {
                type: "prime_offer",
                value: 35,
                price: 42.9,
                action: "gbrappi://com.grability.rappi?goto=view_prime_modal&source={SOURCE}",
                is_prime_exclusive: true,
                chevron: {
                    deeplink:
                        "gbrappi://com.grability.rappi?goto=view_prime_modal&source={SOURCE}",
                },
                apply_to_user: false,
                tag_label: "S/42.90 con Prime",
            },
        ],
        ad_request_id: "",
        ad_provider_metadata: "",
        ads_image: "",
        dietary_tags: null,
    },
    {
        id: "13031_2092179266",
        name: "Duo Combinado",
        description:
            "2 Combinados taypa (arroz chaufa de pollo y pollo con verduras), 2 gaseosas 500ml a elección. promoción válida del 19/09/2023 hasta 31/10/2023. stock mínimo de 100 unidades. razon social: alert del peru s.a. y ruc: 20101869947.",
        image: "tmp223470558150501058714374085.png",
        index: 2,
        tablecloth: "tablecloth.png",
        need_image: true,
        need_topping: true,
        has_toppings: true,
        has_recommendations: false,
        is_available: false,
        corridor_id: 172939,
        corridor_name: "Promociones ",
        corridor_index: 1,
        real_price: 55.6,
        price: 55.6,
        schedules: [
            {
                open_time: "10:30:00",
                close_time: "22:00:00",
            },
        ],
        discount_from_go: false,
        store_id: 13031,
        product_id: 2092179266,
        store_name: "",
        quantity: 1,
        is_open_forever: false,
        has_up_sellings: false,
        is_liked: false,
        topping_list: [],
        comment: "",
        have_discount: false,
        second_layer: "",
        quantity_bought: 0,
        is_popular: false,
        super_store_id: 12136,
        brand_name: "",
        in_schedule: true,
        elastic_version: 0,
        last_updated: 1696532677668,
        show_discount_tag: true,
        dietary_restrictions: null,
        discount_percentage: 0,
        minimum_price: -1,
        minimum_price_text: null,
        discounts: [
            {
                type: "prime_offer",
                value: 46,
                price: 29.9,
                action: "gbrappi://com.grability.rappi?goto=view_prime_modal&source={SOURCE}",
                is_prime_exclusive: true,
                chevron: {
                    deeplink:
                        "gbrappi://com.grability.rappi?goto=view_prime_modal&source={SOURCE}",
                },
                apply_to_user: false,
                tag_label: "S/29.90 con Prime",
            },
        ],
        ad_request_id: "",
        ad_provider_metadata: "",
        ads_image: "",
        dietary_tags: null,
    },
    {
        id: "13031_2092179267",
        name: "Duo Mosticrunch",
        description:
            "2 Mosticrunch (arroz chaufa de pollo, papas fritas y muslo de pollo empanizado), 2 gaseosas 500ml a elección. promoción válida del 19/09/2023 hasta 31/10/2023. stock mínimo de 100 unidades. razon social: alert del peru s.a. y ruc: 20101869947.",
        image: "tmp223470748471205948383600426.png",
        index: 3,
        tablecloth: "tablecloth.png",
        need_image: true,
        need_topping: true,
        has_toppings: true,
        has_recommendations: false,
        is_available: false,
        corridor_id: 172939,
        corridor_name: "Promociones ",
        corridor_index: 1,
        real_price: 61.6,
        price: 61.6,
        schedules: [
            {
                open_time: "10:30:00",
                close_time: "22:00:00",
            },
        ],
        discount_from_go: false,
        store_id: 13031,
        product_id: 2092179267,
        store_name: "",
        quantity: 1,
        is_open_forever: false,
        has_up_sellings: false,
        is_liked: false,
        topping_list: [],
        comment: "",
        have_discount: false,
        second_layer: "",
        quantity_bought: 0,
        is_popular: false,
        super_store_id: 12136,
        brand_name: "",
        in_schedule: true,
        elastic_version: 0,
        last_updated: 1696532677668,
        show_discount_tag: true,
        dietary_restrictions: null,
        discount_percentage: 0,
        minimum_price: -1,
        minimum_price_text: null,
        discounts: [
            {
                type: "prime_offer",
                value: 35,
                price: 39.9,
                action: "gbrappi://com.grability.rappi?goto=view_prime_modal&source={SOURCE}",
                is_prime_exclusive: true,
                chevron: {
                    deeplink:
                        "gbrappi://com.grability.rappi?goto=view_prime_modal&source={SOURCE}",
                },
                apply_to_user: false,
                tag_label: "S/39.90 con Prime",
            },
        ],
        ad_request_id: "",
        ad_provider_metadata: "",
        ads_image: "",
        dietary_tags: null,
    },
    {
        id: "13031_2092149565",
        name: "Combo Encájate Tipakay",
        description:
            "1 Encájate tipakay, 2 wantanes, salsa tamarindo, 1 gaseosa personal 500ml a elección. promoción válida del 07/08/2023 hasta 31/12/2023. stock mínimo de 100 unidades. razon social: alert del peru s.a. y ruc: 20101869947.",
        image: "tmp2070318912926835562427696526.png",
        index: 6,
        tablecloth: "tablecloth.png",
        need_image: true,
        need_topping: true,
        has_toppings: true,
        has_recommendations: false,
        is_available: false,
        corridor_id: 172939,
        corridor_name: "Promociones ",
        corridor_index: 1,
        real_price: 27.7,
        price: 27.7,
        schedules: [
            {
                open_time: "10:30:00",
                close_time: "22:00:00",
            },
        ],
        discount_from_go: true,
        store_id: 13031,
        product_id: 2092149565,
        store_name: "",
        quantity: 1,
        is_open_forever: false,
        has_up_sellings: false,
        is_liked: false,
        topping_list: [],
        comment: "",
        have_discount: false,
        second_layer: "",
        quantity_bought: 0,
        is_popular: false,
        super_store_id: 12136,
        brand_name: "",
        in_schedule: true,
        elastic_version: 0,
        last_updated: 1696532677668,
        show_discount_tag: true,
        dietary_restrictions: null,
        discount_percentage: 28,
        minimum_price: -1,
        minimum_price_text: null,
        discounts: [
            {
                type: "global_offer",
                value: 28,
                price: 19.9,
                action: "",
                is_prime_exclusive: false,
                apply_to_user: true,
            },
        ],
        ad_request_id: "",
        ad_provider_metadata: "",
        ads_image: "",
        dietary_tags: null,
    },
    {
        id: "13031_2092149564",
        name: "Combo Encájate Chi Jau Kay",
        description:
            "1 Encájate chi jau kay, 2 wantanes, salsa tamarindo, 1 gaseosa personal 500ml a elección. promoción válida del 07/08/2023 hasta 31/12/2023. stock mínimo de 100 unidades. razon social: alert del peru s.a. y ruc: 20101869947.",
        image: "tmp2070317315080647178421859529.png",
        index: 7,
        tablecloth: "tablecloth.png",
        need_image: true,
        need_topping: true,
        has_toppings: true,
        has_recommendations: false,
        is_available: false,
        corridor_id: 172939,
        corridor_name: "Promociones ",
        corridor_index: 1,
        real_price: 27.7,
        price: 27.7,
        schedules: [
            {
                open_time: "10:30:00",
                close_time: "22:00:00",
            },
        ],
        discount_from_go: true,
        store_id: 13031,
        product_id: 2092149564,
        store_name: "",
        quantity: 1,
        is_open_forever: false,
        has_up_sellings: false,
        is_liked: false,
        topping_list: [],
        comment: "",
        have_discount: false,
        second_layer: "",
        quantity_bought: 0,
        is_popular: false,
        super_store_id: 12136,
        brand_name: "",
        in_schedule: true,
        elastic_version: 0,
        last_updated: 1696532677668,
        show_discount_tag: true,
        dietary_restrictions: null,
        discount_percentage: 28,
        minimum_price: -1,
        minimum_price_text: null,
        discounts: [
            {
                type: "global_offer",
                value: 28,
                price: 19.9,
                action: "",
                is_prime_exclusive: false,
                apply_to_user: true,
            },
        ],
        ad_request_id: "",
        ad_provider_metadata: "",
        ads_image: "",
        dietary_tags: null,
    },
    {
        id: "13031_2092149566",
        name: "Combo Encájate Alitas",
        description:
            "1 Encájate alitas, 2 wantanes, salsa tamarindo, 1 gaseosa personal 500ml a elección. promoción válida del 07/08/2023 hasta 31/12/2023. stock mínimo de 100 unidades. razon social: alert del peru s.a. y ruc: 20101869947.",
        image: "tmp207032054794376663967005922.png",
        index: 8,
        tablecloth: "tablecloth.png",
        need_image: true,
        need_topping: true,
        has_toppings: true,
        has_recommendations: false,
        is_available: false,
        corridor_id: 172939,
        corridor_name: "Promociones ",
        corridor_index: 1,
        real_price: 28.7,
        price: 28.7,
        schedules: [
            {
                open_time: "10:30:00",
                close_time: "22:00:00",
            },
        ],
        discount_from_go: true,
        store_id: 13031,
        product_id: 2092149566,
        store_name: "",
        quantity: 1,
        is_open_forever: false,
        has_up_sellings: false,
        is_liked: false,
        topping_list: [],
        comment: "",
        have_discount: false,
        second_layer: "",
        quantity_bought: 0,
        is_popular: false,
        super_store_id: 12136,
        brand_name: "",
        in_schedule: true,
        elastic_version: 0,
        last_updated: 1696532677668,
        show_discount_tag: true,
        dietary_restrictions: null,
        discount_percentage: 31,
        minimum_price: -1,
        minimum_price_text: null,
        discounts: [
            {
                type: "global_offer",
                value: 31,
                price: 19.9,
                action: "",
                is_prime_exclusive: false,
                apply_to_user: true,
            },
        ],
        ad_request_id: "",
        ad_provider_metadata: "",
        ads_image: "",
        dietary_tags: null,
    },
    {
        id: "13031_2092149567",
        name: "Combo Encájate Honey Chicken",
        description:
            "1 Encájate honey chicken, 2 wantanes, salsa tamarindo, 1 gaseosa personal 500ml a elección. promoción válida del 07/08/2023 hasta 31/12/2023. stock mínimo de 100 unidades. razon social: alert del peru s.a. y ruc: 20101869947.",
        image: "tmp2070322115187345275788610923.png",
        index: 9,
        tablecloth: "tablecloth.png",
        need_image: true,
        need_topping: true,
        has_toppings: true,
        has_recommendations: false,
        is_available: false,
        corridor_id: 172939,
        corridor_name: "Promociones ",
        corridor_index: 1,
        real_price: 27.7,
        price: 27.7,
        schedules: [
            {
                open_time: "10:30:00",
                close_time: "22:00:00",
            },
        ],
        discount_from_go: true,
        store_id: 13031,
        product_id: 2092149567,
        store_name: "",
        quantity: 1,
        is_open_forever: false,
        has_up_sellings: false,
        is_liked: false,
        topping_list: [],
        comment: "",
        have_discount: false,
        second_layer: "",
        quantity_bought: 0,
        is_popular: false,
        super_store_id: 12136,
        brand_name: "",
        in_schedule: true,
        elastic_version: 0,
        last_updated: 1696532677668,
        show_discount_tag: true,
        dietary_restrictions: null,
        discount_percentage: 28,
        minimum_price: -1,
        minimum_price_text: null,
        discounts: [
            {
                type: "global_offer",
                value: 28,
                price: 19.9,
                action: "",
                is_prime_exclusive: false,
                apply_to_user: true,
            },
        ],
        ad_request_id: "",
        ad_provider_metadata: "",
        ads_image: "",
        dietary_tags: null,
    },
    {
        id: "13031_2092149568",
        name: "Combo Encájate Mandarin Chicken",
        description:
            "1 Encájate mandarin chicken, 2 wantanes, salsa tamarindo, 1 gaseosa personal 500ml a elección. promoción válida del 07/08/2023 hasta 31/12/2023. stock mínimo de 100 unidades. razon social: alert del peru s.a. y ruc: 20101869947.",
        image: "tmp207032371454093252716477544.png",
        index: 10,
        tablecloth: "tablecloth.png",
        need_image: true,
        need_topping: true,
        has_toppings: true,
        has_recommendations: false,
        is_available: false,
        corridor_id: 172939,
        corridor_name: "Promociones ",
        corridor_index: 1,
        real_price: 27.7,
        price: 27.7,
        schedules: [
            {
                open_time: "10:30:00",
                close_time: "22:00:00",
            },
        ],
        discount_from_go: true,
        store_id: 13031,
        product_id: 2092149568,
        store_name: "",
        quantity: 1,
        is_open_forever: false,
        has_up_sellings: false,
        is_liked: false,
        topping_list: [],
        comment: "",
        have_discount: false,
        second_layer: "",
        quantity_bought: 0,
        is_popular: false,
        super_store_id: 12136,
        brand_name: "",
        in_schedule: true,
        elastic_version: 0,
        last_updated: 1696532677668,
        show_discount_tag: true,
        dietary_restrictions: null,
        discount_percentage: 28,
        minimum_price: -1,
        minimum_price_text: null,
        discounts: [
            {
                type: "global_offer",
                value: 28,
                price: 19.9,
                action: "",
                is_prime_exclusive: false,
                apply_to_user: true,
            },
        ],
        ad_request_id: "",
        ad_provider_metadata: "",
        ads_image: "",
        dietary_tags: null,
    },
    {
        id: "13031_2092149569",
        name: "Dúo Encájate Al Wok",
        description:
            "1 Encájate honey chicken, 1  encájate chi jau kay, 4 wantanes con salsa tamarindo, 2 gaseosas 500ml a elección. promoción válida del 07/08/2023 hasta 31/12/2023. stock mínimo de 100 unidades. razon social: alert del peru s.a. y ruc: 20101869947.",
        image: "tmp2070325311712850365706730786.png",
        index: 11,
        tablecloth: "tablecloth.png",
        need_image: true,
        need_topping: true,
        has_toppings: true,
        has_recommendations: false,
        is_available: false,
        corridor_id: 172939,
        corridor_name: "Promociones ",
        corridor_index: 1,
        real_price: 54.9,
        price: 54.9,
        schedules: [
            {
                open_time: "10:30:00",
                close_time: "22:00:00",
            },
        ],
        discount_from_go: true,
        store_id: 13031,
        product_id: 2092149569,
        store_name: "",
        quantity: 1,
        is_open_forever: false,
        has_up_sellings: false,
        is_liked: false,
        topping_list: [],
        comment: "",
        have_discount: false,
        second_layer: "",
        quantity_bought: 0,
        is_popular: false,
        super_store_id: 12136,
        brand_name: "",
        in_schedule: true,
        elastic_version: 0,
        last_updated: 1696532677668,
        show_discount_tag: true,
        dietary_restrictions: null,
        discount_percentage: 36,
        minimum_price: -1,
        minimum_price_text: null,
        discounts: [
            {
                type: "global_offer",
                value: 36,
                price: 34.9,
                action: "",
                is_prime_exclusive: false,
                apply_to_user: true,
            },
        ],
        ad_request_id: "",
        ad_provider_metadata: "",
        ads_image: "",
        dietary_tags: null,
    },
    {
        id: "13031_2092149570",
        name: "Super Dúo Alitas Al Wok",
        description:
            "2 Encájate alitas: arroz chaufa de pollo individual acompañado de 4 alitas al wok con salsa limón y canela china. promoción válida del 07/08/2023 hasta 31/12/2023. stock mínimo de 100 unidades. razon social: alert del peru s.a. y ruc: 20101869947.",
        image: "tmp207032701476445579097223788.png",
        index: 12,
        tablecloth: "tablecloth.png",
        need_image: true,
        need_topping: true,
        has_toppings: true,
        has_recommendations: false,
        is_available: false,
        corridor_id: 172939,
        corridor_name: "Promociones ",
        corridor_index: 1,
        real_price: 37.8,
        price: 37.8,
        schedules: [
            {
                open_time: "10:30:00",
                close_time: "22:00:00",
            },
        ],
        discount_from_go: true,
        store_id: 13031,
        product_id: 2092149570,
        store_name: "",
        quantity: 1,
        is_open_forever: false,
        has_up_sellings: false,
        is_liked: false,
        topping_list: [],
        comment: "",
        have_discount: false,
        second_layer: "",
        quantity_bought: 0,
        is_popular: false,
        super_store_id: 12136,
        brand_name: "",
        in_schedule: true,
        elastic_version: 0,
        last_updated: 1696532677668,
        show_discount_tag: true,
        dietary_restrictions: null,
        discount_percentage: 21,
        minimum_price: -1,
        minimum_price_text: null,
        discounts: [
            {
                type: "global_offer",
                value: 21,
                price: 29.9,
                action: "",
                is_prime_exclusive: false,
                apply_to_user: true,
            },
        ],
        ad_request_id: "",
        ad_provider_metadata: "",
        ads_image: "",
        dietary_tags: null,
    },
    {
        id: "13031_2092149571",
        name: "Dúo Al Wok De Aeropuertos",
        description:
            "1 Aeropuerto cecina, 1 aeropuerto lomo saltado, 2 gaseosas 500ml a elección. promoción válida del 07/08/2023 hasta 31/12/2023. stock mínimo de 100 unidades. razon social: alert del peru s.a. y ruc: 20101869947.",
        image: "tmp2070328310690528330993720351.png",
        index: 13,
        tablecloth: "tablecloth.png",
        need_image: true,
        need_topping: true,
        has_toppings: true,
        has_recommendations: false,
        is_available: false,
        corridor_id: 172939,
        corridor_name: "Promociones ",
        corridor_index: 1,
        real_price: 61.6,
        price: 61.6,
        schedules: [
            {
                open_time: "10:30:00",
                close_time: "22:00:00",
            },
        ],
        discount_from_go: true,
        store_id: 13031,
        product_id: 2092149571,
        store_name: "",
        quantity: 1,
        is_open_forever: false,
        has_up_sellings: false,
        is_liked: false,
        topping_list: [],
        comment: "",
        have_discount: false,
        second_layer: "",
        quantity_bought: 0,
        is_popular: false,
        super_store_id: 12136,
        brand_name: "",
        in_schedule: true,
        elastic_version: 0,
        last_updated: 1696532677668,
        show_discount_tag: true,
        dietary_restrictions: null,
        discount_percentage: 35,
        minimum_price: -1,
        minimum_price_text: null,
        discounts: [
            {
                type: "global_offer",
                value: 35,
                price: 39.9,
                action: "",
                is_prime_exclusive: false,
                apply_to_user: true,
            },
        ],
        ad_request_id: "",
        ad_provider_metadata: "",
        ads_image: "",
        dietary_tags: null,
    },
    {
        id: "13031_2092149572",
        name: "Banquete Familiar",
        description:
            "Elige tus 4 encájate con tu potaje favorito: encájate chi jau kay(salado), encájate alitas (salado), encájate tipakay (dulce),  encájate honey chicken (dulce), acompañado de 8 wantanes con salsa tamarindo. promoción válida del 07/08/2023 hasta 31/12/2023.",
        image: "tmp207032992951047494761008646.png",
        index: 14,
        tablecloth: "tablecloth.png",
        need_image: true,
        need_topping: true,
        has_toppings: true,
        has_recommendations: false,
        is_available: false,
        corridor_id: 172939,
        corridor_name: "Promociones ",
        corridor_index: 1,
        real_price: 90,
        price: 90,
        schedules: [
            {
                open_time: "10:30:00",
                close_time: "22:00:00",
            },
        ],
        discount_from_go: true,
        store_id: 13031,
        product_id: 2092149572,
        store_name: "",
        quantity: 1,
        is_open_forever: false,
        has_up_sellings: false,
        is_liked: false,
        topping_list: [],
        comment: "",
        have_discount: false,
        second_layer: "",
        quantity_bought: 0,
        is_popular: false,
        super_store_id: 12136,
        brand_name: "",
        in_schedule: true,
        elastic_version: 0,
        last_updated: 1696532677668,
        show_discount_tag: true,
        dietary_restrictions: null,
        discount_percentage: 45,
        minimum_price: -1,
        minimum_price_text: null,
        discounts: [
            {
                type: "global_offer",
                value: 45,
                price: 49.9,
                action: "",
                is_prime_exclusive: false,
                apply_to_user: true,
            },
        ],
        ad_request_id: "",
        ad_provider_metadata: "",
        ads_image: "",
        dietary_tags: null,
    },
    {
        id: "13031_2092149573",
        name: "Banquete Súper Familiar",
        description:
            "2 Combinados a elección, 2 combowok a elección, 10 wantanes con salsa tamarindo. promoción válida del 07/08/2023 hasta 31/12/2023. stock mínimo de 100 unidades. razon social: alert del peru s.a. y ruc: 20101869947.",
        image: "tmp2070331615363718604441647650.png",
        index: 15,
        tablecloth: "tablecloth.png",
        need_image: true,
        need_topping: true,
        has_toppings: true,
        has_recommendations: false,
        is_available: false,
        corridor_id: 172939,
        corridor_name: "Promociones ",
        corridor_index: 1,
        real_price: 117.77,
        price: 117.77,
        schedules: [
            {
                open_time: "10:30:00",
                close_time: "22:00:00",
            },
        ],
        discount_from_go: true,
        store_id: 13031,
        product_id: 2092149573,
        store_name: "",
        quantity: 1,
        is_open_forever: false,
        has_up_sellings: false,
        is_liked: false,
        topping_list: [],
        comment: "",
        have_discount: false,
        second_layer: "",
        quantity_bought: 0,
        is_popular: false,
        super_store_id: 12136,
        brand_name: "",
        in_schedule: true,
        elastic_version: 0,
        last_updated: 1696532677668,
        show_discount_tag: true,
        dietary_restrictions: null,
        discount_percentage: 41,
        minimum_price: -1,
        minimum_price_text: null,
        discounts: [
            {
                type: "global_offer",
                value: 41,
                price: 69.9,
                action: "",
                is_prime_exclusive: false,
                apply_to_user: true,
            },
        ],
        ad_request_id: "",
        ad_provider_metadata: "",
        ads_image: "",
        dietary_tags: null,
    },
];

export default dataList;
